# Generated by Django 5.0.3 on 2024-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.TextField(null=True)),
                ('ans', models.TextField(null=True)),
                ('opt1', models.TextField(null=True)),
                ('opt2', models.TextField(null=True)),
                ('opt3', models.TextField(null=True)),
                ('opt4', models.TextField(null=True)),
            ],
        ),
    ]
