# Generated by Django 5.0.3 on 2024-03-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ_Gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.TextField(null=True)),
                ('ans', models.TextField(null=True)),
                ('opt1', models.TextField(null=True)),
                ('opt2', models.TextField(null=True)),
                ('opt3', models.TextField(null=True)),
                ('opt4', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.AddField(
            model_name='mcq_gen',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.quizheading'),
        ),
    ]
