# Generated by Django 5.0.3 on 2024-03-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_mcq_gen_quizheading_delete_mcq_mcq_gen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_gen',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.quizheading'),
        ),
    ]
