# Generated by Django 5.0.3 on 2024-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_mcq_gen_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_gen',
            name='name',
        ),
        migrations.AddField(
            model_name='mcq_gen',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
